services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - path: startup/.env.database
        required: true
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U admin -d music_play
      start_period: 5s
  storage:
    image: dxflrs/garage:v2.3.0
    container_name: storage
    command: /garage server --single-node --default-bucket --default-access-key
    env_file:
      - path: startup/.env.storage
        required: true
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
        - ${PWD}/startup/garage.toml:/etc/garage.toml
  search:
    image: solr:latest
    container_name: search
    ports:
      - 8983:8983
    healthcheck:
      test: solr status
      start_period: 5s
  message:
      image: rabbitmq:4.2.5-management-alpine
      container_name: message
      env_file:
        - path: startup/.env.message
          required: true
      ports:
        - 15672:15672
        - 5672:5672
      healthcheck:
        test: rabbitmq-diagnostics -q ping
        start_period: 5s
  auth:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: auth
    command: start-dev --health-enabled=true --verbose --import-realm --spi-events-listener--jboss-logging--success-level=info
    env_file:
      - path: startup/.env.auth
        required: true
    ports:
      - 8081:8080
      - 9000:9000
    volumes:
      - ${PWD}/startup/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ${PWD}/startup/KeycloakSpi-1.0-SNAPSHOT.jar:/opt/keycloak/providers/KeycloakSpi-1.0-SNAPSHOT.jar
    depends_on:
      message:
        condition: service_healthy
  startup:
    # image: rewrap0998/music_play-startup
    build: startup/seedData
    container_name: startup
    env_file:
      - path: startup/.env
        required: true
      - path: startup/.env.docker
        required: true
    depends_on:
      database:
        condition: service_healthy
      search:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8080/isReady || exit 1
      start_period: 2m
  backend:
    # image: rewrap0998/music_play-backend
    build: backend
    container_name: backend
    env_file:
      - path: startup/.env
        required: true
      - path: startup/.env.docker
        required: true
    ports:
      - 8080:8080
    depends_on:
      startup:
        condition: service_healthy
    healthcheck:
      test: curl -f --silent localhost:8080/actuator/health | grep UP || exit 1
      start_period: 5s
      interval: 10s
  frontend:
    # image: rewrap0998/music_play-frontend
    build: frontend
    container_name: frontend
    env_file:
      - path: startup/.env.frontend
        required: true
      - path: startup/.env.frontend.docker
        required: true
    ports:
      - 8443:8080
    depends_on:
      backend:
        condition: service_healthy